version: '3.8'
services: 
    front-end:
      container_name: front-end
      build:
        context: ./warehouse-front
        dockerfile: Dockerfile
      volumes:
       - ./warehouse-front:/usr/app
       - /usr/app/node_modules
      ports:
        - 3000:3000
      environment:
        - CHOKIDAR_USEPOLLING=true
        - REACT_APP_INVENTORY_SERVICE_URL=${REACT_APP_INVENTORY_SERVICE_URL}
    
    inventory-service:
      container_name: inventory-service
      build:
        context: ./inventory-service
        dockerfile: Dockerfile
      volumes:
       - ./inventory-service:/usr/app
       - /usr/app/node_modules
      ports:
        - 4000:4000
      environment:
        - CHOKIDAR_USEPOLLING=true
        - MONGO_URI=${MONGO_URI}
    
    inventory-worker:
      container_name: inventory-worker
      build:
        context: ./inventory-worker
        dockerfile: Dockerfile
      volumes:
       - ./inventory-worker:/usr/app
       - /usr/app/node_modules
      ports:
        - 4001:4001
      environment:
        - CHOKIDAR_USEPOLLING=true
        - MONGO_URI=${MONGO_URI}

    order-service:
      container_name: order-service
      build:
        context: ./order-service
        dockerfile: Dockerfile
      volumes:
       - ./order-service:/usr/app
       - /usr/app/node_modules
      ports:
        - 5000:5000
      environment:
        - CHOKIDAR_USEPOLLING=true
        - MONGO_URI=${MONGO_URI}
